apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: ek.external.demo-dependencies.learn.1.0.0
spec:
  refName: ek.external.demo-dependencies.learn
  version: 1.0.0
  releaseNotes: |
    Initial release of the demo dependencies elasticsearch and kibana package
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        namespace:
          type: string
          default: elasticsearch-kibana
        elasticsearch:
          type: object
          additionalProperties: false
          properties:
            ingress:
              type: object
              additionalProperties: false
              properties:
                virtual_host_fqdn:
                  type: string
                  default: ""
        kibana:
          type: object
          additionalProperties: false
          properties:
            ingress:
              type: object
              additionalProperties: false
              properties:
                virtual_host_fqdn:
                  type: string
                  default: ""
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/doddatpivotal/demo-dependencies
          ref: origin/main
          subPath: ek-package
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
