# relok8s image hints file
# This file makes this Helm Chart relocatable by relok8s
# More info here https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes
#
# minio chart

# minio image
- "{{.image.registry}}/{{.image.repository}}:{{.image.tag}}"
# minio-client image
- "{{.clientImage.registry}}/{{.clientImage.repository}}:{{.clientImage.tag}}"
# tac-shell image
- "{{.volumePermissions.image.registry}}/{{.volumePermissions.image.repository}}:{{.volumePermissions.image.tag}}"

