#@ load("@ytt:data", "data")  # for reading data values (generated via ytt's data-values-schema-inspect mode).
#@ load("@ytt:yaml", "yaml")  # for dynamically decoding the output of ytt's data-values-schema-inspect
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: #@ "minio.external.demo-dependencies.learn." + data.values.version
spec:
  refName: minio.external.demo-dependencies.learn
  version: #@ data.values.version
  releaseNotes: |
    Initial release of the demo dependencies minio package
  valuesSchema:
    openAPIv3: #@ yaml.decode(data.values.openapi)["components"]["schemas"]["dataValues"]
  template:
    spec:
      fetch:
        - git:
            url: https://github.com/doddatpivotal/demo-dependencies
            ref: origin/main
            subPath: #@ "packages/minio/" + data.values.version + "/bundle"
      template:
        - ytt:
            ignoreUnknownComments: true
            paths:
            - '-'
            #! This was a really great idea to just use the same values file from helm and ytt.
            - chart/values.yaml
            - config/
        - helmTemplate:
            path: chart/
            valuesFrom:
            - path: "-"

        - kbld:
            paths:
            - '-'
            - .imgpkg/images.yml
      deploy:
      - kapp: {}
