apiVersion: vendir.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.12.0
directories:
- path: bundle/chart
  contents:
  - path: .
    helmChart:
      name: minio
      version: "10.1.8"
      repository:
        url: https://charts.app-catalog.vmware.com/demo
# - path: bundle/config
#   contents:
#   - path: .
#     directory:
#       path: manifests