#@data/values-schema
---
#@schema/desc "Namespace to deploy"
namespace: "minio"
auth:
  #@schema/desc "Root password"
  rootPassword: "admin"
#@schema/desc "Bucket Name"
defaultBuckets: backup
persistence:
  #@schema/desc "Persistent volume size"
  size: 40G
