apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: minio.external.demo-dependencies.learn.1.0.0
spec:
  refName: minio.external.demo-dependencies.learn
  version: 1.0.0
  releaseNotes: |
    Initial release of the demo dependencies minio package
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        namespace:
          type: string
          description: Namespace to deploy
          default: minio
        auth:
          type: object
          additionalProperties: false
          properties:
            rootPassword:
              type: string
              description: Root password
              default: admin
        defaultBuckets:
          type: string
          description: Bucket Name
          default: backup
        persistence:
          type: object
          additionalProperties: false
          properties:
            size:
              type: string
              description: Persistent volume size
              default: 40G
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/doddatpivotal/demo-dependencies
          ref: origin/main
          subPath: packages/minio/1.0.0/bundle
      template:
      - helmTemplate:
          namespace: minio
          path: chart/
      - ytt:
          ignoreUnknownComments: true
          paths:
          - '-'
          - chart/values.yaml
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
