#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")


#@overlay/match by=overlay.all
---

auth:
  rootUser: admin
  rootPassword: #@ data.values.auth.rootPassword
service:
  type: LoadBalancer
defaultBuckets: #@ data.values.defaultBuckets
persistence:
  size: #@ data.values.persistence.size