#! This to set non-configurable overrides to the default.values.yaml

#@ load("@ytt:overlay", "overlay")


#@overlay/match by=overlay.all
---
auth:
  rootUser: admin
service:
  type: LoadBalancer
defaultBuckets: backup
